# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hundkatzenschweinerei
email: team@hund-katze-schweinerei.de
description: > # this means to ignore newlines until "baseurl:"
  Hier erfahrt ihr alles über Hundkatzenschweinerei und den Searchmetrics Seo Contest 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hund-katze-schweinerei.de" # the base hostname & protocol for your site
unpublished: false
exclude: [hundkatzenschweinerei.iml, deploy.sh]
twitter_username: hundkatzeschwei
github_username:  hundkatzenschweinerei

# Build settings
markdown: kramdown


